sonar.projectKey=smart-frontend
sonar.projectName=S.M.A.R.T - Smart Mobility Platform
sonar.projectVersion=1.1.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/test/setup.ts,**/*.d.ts
