version: '3.8'

services:
  smart-messaging:
    build: .
    container_name: smart-messaging-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=shark.rmq.cloudamqp.com
      - SPRING_RABBITMQ_PORT=5671
      - SPRING_RABBITMQ_USERNAME=upzhvdpi
      - SPRING_RABBITMQ_PASSWORD=uQeQBUACo1mXOIuYq2Rta87dczLjEkHa
      - SPRING_RABBITMQ_VIRTUAL_HOST=upzhvdpi
      - SPRING_RABBITMQ_SSL_ENABLED=true

