spring:
  application:
    name: smart-messaging

  rabbitmq:
    host: shark.rmq.cloudamqp.com
    port: 5671
    username: upzhvdpi
    password: uQeQBUACo1mXOIuYq2Rta87dczLjEkHa
    virtual-host: upzhvdpi
    ssl:
      enabled: true

    # Reintentos automáticos si RabbitMQ no está disponible al arrancar
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-interval: 30000
        multiplier: 2.0

    # Configuración del listener (consumidores)
    listener:
      simple:
        acknowledge-mode: manual   # manual-ack para mayor control y DLX
        prefetch: 1              # 1 mensaje a la vez por consumidor

server:
  port: 8080

logging:
  level:
    com.smart.messaging: DEBUG
    org.springframework.amqp: INFO
